// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjaLjkuxLzn3TmFOStTTPZXGQXTA5L1Ww',
    appId: '1:826321517336:web:7d039bc5de91544f06bc6d',
    messagingSenderId: '826321517336',
    projectId: 'weave-the-border-a7d58',
    authDomain: 'weave-the-border-a7d58.firebaseapp.com',
    storageBucket: 'weave-the-border-a7d58.firebasestorage.app',
    measurementId: 'G-N9SNM3HD2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUlFT9hxwo0Z4OmyGakZItAqJXX23ZGNE',
    appId: '1:826321517336:android:5d891033ff7f80f506bc6d',
    messagingSenderId: '826321517336',
    projectId: 'weave-the-border-a7d58',
    storageBucket: 'weave-the-border-a7d58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYxey3tDUO9cYPdAle31Uk71DjiGTORk',
    appId: '1:826321517336:ios:c604c96aadf6798b06bc6d',
    messagingSenderId: '826321517336',
    projectId: 'weave-the-border-a7d58',
    storageBucket: 'weave-the-border-a7d58.firebasestorage.app',
    iosBundleId: 'jp.stady_start.weave_the_border',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYxey3tDUO9cYPdAle31Uk71DjiGTORk',
    appId: '1:826321517336:ios:c604c96aadf6798b06bc6d',
    messagingSenderId: '826321517336',
    projectId: 'weave-the-border-a7d58',
    storageBucket: 'weave-the-border-a7d58.firebasestorage.app',
    iosBundleId: 'jp.stady_start.weave_the_border',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjaLjkuxLzn3TmFOStTTPZXGQXTA5L1Ww',
    appId: '1:826321517336:web:aa525914af0955b906bc6d',
    messagingSenderId: '826321517336',
    projectId: 'weave-the-border-a7d58',
    authDomain: 'weave-the-border-a7d58.firebaseapp.com',
    storageBucket: 'weave-the-border-a7d58.firebasestorage.app',
    measurementId: 'G-WFDSVP2T1T',
  );

}